### ISSUE TITLE
How to best add a new project?

### ISSUE THREAD

**Issue by matteoettam09** [edarchimbaud/awesome-systematic-trading#8]
Hi, 
great repo. My name is Matteo and I work at [CrunchDAO](https://www.crunchdao.com/). Our daily work covers topics associated with traditional Quant Finance, Machine Learning and cryptocurrencies.

Would it be possible to add our project here? Our [tournaments](https://account.crunchdao.com/hub) are looking for new people interested in the topics every day! 

Let me know if this is possible and how to best do that with a pull request! 

Cheers

**Comment by edarchimbaud** [comment]
Hi Matteo, thank you for contacting me. I see two possibilities:
1. Add a section at the bottom of the page "Systematic Trading Tournaments" with Numerai, Quantiacs, and CrunchDAO, sorted by decreasing monthly number of visitors (respectively 110k, 60k, 7k)
2. Consider a partnership for a top-of-page insert
Option 1, I will let you prepare a PR. Option 2, please DM me on Twitter @edarchimbaud to discuss.
